POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@mail.com",
    "password": "admin54321"
}

### login
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "admin54321"
}

### users
GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQG1haWwuY29tIiwiaWQiOjEsImlhdCI6MTcwNjU3ODgwMSwiZXhwIjoxNzA2NTc4ODYxfQ.lmp1aNiIpSYm_99oYvyL78xtoSN2jIXh4iTalnNIk9I
