GET http://localhost:3000/producto

### crear producto
POST http://localhost:3000/producto
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQG1haWwuY29tIiwiaWQiOjEsImlhdCI6MTcwOTI1Nzk5MCwiZXhwIjoxNzA5MjYxNTkwfQ.cdeVkr7FF_qVajMdgiKQf6n5Q548sL2de6UyMYiiBYE

{
    "nombre": "ESCRITORIO",
    "precio": "1599.98",
    "stock": 5,
    "categoriaId": 1
}

### modificar producto
PATCH  http://localhost:3000/producto/10
Content-Type: application/json

{
    "nombre": "PARLANTES",
    "precio": "199.98",
    "stock": 5,
    "categoriaId": 1
}

### Buscar por nombre

GET http://localhost:3000/producto/back?page=1&q=MO&sort=asc
